- bicycle.csv 파일을 읽어 들입니다
- 데이터프레임 편수 df 사용 조회

In [1]:
import pandas as pd

In [5]:
file_path='./data/bicycle.csv'
df= pd.read_csv(file_path,encoding='euc-kr')
# 안열리면 원본 파일을 utf-8로 저장 해서 다시 열기 or cp-949
df

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.0,10.0,NaN
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,NaN,10.0,1380.0
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0
...,...,...,...,...,...,...,...,...,...,...,...
415,SPB-12116,2019-11-15 4:22,112,극동방송국 앞,5.0,2019-11-15 4:33,101,(구)합정동 주민센터,1.0,11.0,2200.0
416,SPB-17768,2019-11-15 9:31,103,망원역 2번출구 앞,14.0,2019-11-15 9:37,101,(구)합정동 주민센터,NaN,5.0,NaN
417,SPB-18841,2019-11-15 20:40,113,홍대입구역 2번출구 앞,24.0,2019-11-15 20:53,101,(구)합정동 주민센터,1.0,12.0,2280.0
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.0,10.0,1180.0
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.0,48.0,8100.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   자전거번호    420 non-null    object
 1   대여일시     420 non-null    object
 2   대여소번호    420 non-null    int64
 3   대여소명     420 non-null    object
 4   대여거치대    396 non-null    float64
 5   반납일시     420 non-null    object
 6   반납대여소번호  420 non-null    int64
 7   반납대여소명   420 non-null    object
 8   반납거치대    409 non-null    float64
 9   이용시간     405 non-null    float64
 10  이용거리     404 non-null    float64
dtypes: float64(4), int64(2), object(5)
memory usage: 36.2+ KB

In [11]:
df.isnull()

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,True,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
415,False,False,False,False,False,False,False,False,False,False,False
416,False,False,False,False,False,False,False,False,True,False,True
417,False,False,False,False,False,False,False,False,False,False,False
418,False,False,False,False,False,False,False,False,False,False,False
419,False,False,False,False,False,False,False,False,False,False,False

In [10]:
df.notnull()
# df.isnull()==False

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,True,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,False
3,True,True,True,True,True,True,True,True,False,True,True
4,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...
415,True,True,True,True,True,True,True,True,True,True,True
416,True,True,True,True,True,True,True,True,False,True,False
417,True,True,True,True,True,True,True,True,True,True,True
418,True,True,True,True,True,True,True,True,True,True,True
419,True,True,True,True,True,True,True,True,True,True,True

In [12]:
df[df.notnull()].count()

자전거번호      420
대여일시       420
대여소번호      420
대여소명       420
대여거치대      396
반납일시       420
반납대여소번호    420
반납대여소명     420
반납거치대      409
이용시간       405
이용거리       404
dtype: int64

In [17]:
# True = 1 , False = 0
# 컬럼별 결측값이 있는 행의 갯수 (sum(0)) 조회하기    0 : 행을 뜻한다 
df.isnull().sum(0)

자전거번호       0
대여일시        0
대여소번호       0
대여소명        0
대여거치대      24
반납일시        0
반납대여소번호     0
반납대여소명      0
반납거치대      11
이용시간       15
이용거리       16
dtype: int64

In [18]:
# 행별 결측값이 있는 컬럼의 갯수 (sum(1)) 조회
df.isnull().sum(1)

0      0
1      0
2      1
3      1
4      0
      ..
415    0
416    2
417    0
418    0
419    0
Length: 420, dtype: int64

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 420 entries, 0 to 419
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   자전거번호    420 non-null    object
 1   대여일시     420 non-null    object
 2   대여소번호    420 non-null    int64
 3   대여소명     420 non-null    object
 4   대여거치대    396 non-null    float64
 5   반납일시     420 non-null    object
 6   반납대여소번호  420 non-null    int64
 7   반납대여소명   420 non-null    object
 8   반납거치대    409 non-null    float64
 9   이용시간     405 non-null    float64
 10  이용거리     404 non-null    float64
dtypes: float64(4), int64(2), object(5)
memory usage: 36.2+ KB

In [23]:
# 결측치가 있는 모든행 삭제하기
df.dropna(axis=0)

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0
5,SPB-18401,2019-11-06 8:52,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-06 9:09,3,중랑센터,7.0,11.0,1350.0
6,SPB-18350,2019-11-06 8:35,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-06 9:10,3,중랑센터,2.0,9.0,1390.0
...,...,...,...,...,...,...,...,...,...,...,...
414,SPB-24515,2019-11-15 3:58,112,극동방송국 앞,1.0,2019-11-15 4:08,101,(구)합정동 주민센터,1.0,9.0,1620.0
415,SPB-12116,2019-11-15 4:22,112,극동방송국 앞,5.0,2019-11-15 4:33,101,(구)합정동 주민센터,1.0,11.0,2200.0
417,SPB-18841,2019-11-15 20:40,113,홍대입구역 2번출구 앞,24.0,2019-11-15 20:53,101,(구)합정동 주민센터,1.0,12.0,2280.0
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.0,10.0,1180.0
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.0,48.0,8100.0

In [24]:
# 결측치가 있는 컬럼 삭제하기
df.dropna(axis=1)

,자전거번호,대여일시,대여소번호,대여소명,반납일시,반납대여소번호,반납대여소명
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),2019-11-01 9:01,3,중랑센터
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2019-11-04 8:56,3,중랑센터
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),2019-11-04 8:57,3,중랑센터
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),2019-11-05 8:45,3,중랑센터
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,2019-11-05 12:39,3,중랑센터
...,...,...,...,...,...,...,...
415,SPB-12116,2019-11-15 4:22,112,극동방송국 앞,2019-11-15 4:33,101,(구)합정동 주민센터
416,SPB-17768,2019-11-15 9:31,103,망원역 2번출구 앞,2019-11-15 9:37,101,(구)합정동 주민센터
417,SPB-18841,2019-11-15 20:40,113,홍대입구역 2번출구 앞,2019-11-15 20:53,101,(구)합정동 주민센터
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,2019-11-15 22:05,101,(구)합정동 주민센터
419,SPB-17570,2019-11-15 22:16,391,정동길입구,2019-11-15 23:04,101,(구)합정동 주민센터

In [25]:
df['대여거치대'].dropna(axis=0)

0       3.0
1       2.0
2       1.0
3       1.0
4      11.0
       ...
415     5.0
416    14.0
417    24.0
418    18.0
419     7.0
Name: 대여거치대, Length: 396, dtype: float64

대여소 번호, 대여거치대, 이용시간 3개 컬럼에 결측치가 있으면 행을 삭제하세요

In [33]:
df[['대여거치대','대여소번호','이용시간']].dropna()

     대여거치대  대여소번호  이용시간
0      3.0    646  12.0
1      2.0    646   7.0
2      1.0    646  10.0
3      1.0    646  10.0
4     11.0    512  10.0
..     ...    ...   ...
415    5.0    112  11.0
416   14.0    103   5.0
417   24.0    113  12.0
418   18.0    152  10.0
419    7.0    391  48.0

[382 rows x 3 columns]

In [35]:
# 결측치가 있는 모든 데이터를 0으로 변환하기 
df.fillna(0)

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.0,12.0,1100.0
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.0,7.0,1420.0
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.0,10.0,0.0
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,0.0,10.0,1380.0
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.0,10.0,1650.0
...,...,...,...,...,...,...,...,...,...,...,...
415,SPB-12116,2019-11-15 4:22,112,극동방송국 앞,5.0,2019-11-15 4:33,101,(구)합정동 주민센터,1.0,11.0,2200.0
416,SPB-17768,2019-11-15 9:31,103,망원역 2번출구 앞,14.0,2019-11-15 9:37,101,(구)합정동 주민센터,0.0,5.0,0.0
417,SPB-18841,2019-11-15 20:40,113,홍대입구역 2번출구 앞,24.0,2019-11-15 20:53,101,(구)합정동 주민센터,1.0,12.0,2280.0
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.0,10.0,1180.0
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.0,48.0,8100.0

In [36]:
# 이용거리 컬럼에 있는 결측치만 0으로
df['이용거리'].fillna(0)

0      1100.0
1      1420.0
2         0.0
3      1380.0
4      1650.0
        ...
415    2200.0
416       0.0
417    2280.0
418    1180.0
419    8100.0
Name: 이용거리, Length: 420, dtype: float64

In [37]:
df['이용거리'].fillna('missing')

0       1100.0
1       1420.0
2      missing
3       1380.0
4       1650.0
        ...
415     2200.0
416    missing
417     2280.0
418     1180.0
419     8100.0
Name: 이용거리, Length: 420, dtype: object

In [42]:
# 전체 데이터에서 결측치 값을 각 컬럼의 평균값으로 대체하기 
df.fillna(df.mean())

C:\Users\82102\AppData\Local\Temp\ipykernel_10192\4043654700.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean())

,자전거번호,대여일시,대여소번호,대여소명,대여거치대,반납일시,반납대여소번호,반납대여소명,반납거치대,이용시간,이용거리
0,SPB-23220,2019-11-01 8:48,646,장한평역 1번출구 (국민은행앞),3.0,2019-11-01 9:01,3,중랑센터,7.000000,12.0,1100.000000
1,SPB-16216,2019-11-04 8:38,646,장한평역 1번출구 (국민은행앞),2.0,2019-11-04 8:56,3,중랑센터,2.000000,7.0,1420.000000
2,SPB-21097,2019-11-04 8:46,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-04 8:57,3,중랑센터,7.000000,10.0,2679.678218
3,SPB-22292,2019-11-05 8:34,646,장한평역 1번출구 (국민은행앞),1.0,2019-11-05 8:45,3,중랑센터,2.831296,10.0,1380.000000
4,SPB-07935,2019-11-05 12:29,512,뚝섬역 1번 출구 옆,11.0,2019-11-05 12:39,3,중랑센터,7.000000,10.0,1650.000000
...,...,...,...,...,...,...,...,...,...,...,...
415,SPB-12116,2019-11-15 4:22,112,극동방송국 앞,5.0,2019-11-15 4:33,101,(구)합정동 주민센터,1.000000,11.0,2200.000000
416,SPB-17768,2019-11-15 9:31,103,망원역 2번출구 앞,14.0,2019-11-15 9:37,101,(구)합정동 주민센터,2.831296,5.0,2679.678218
417,SPB-18841,2019-11-15 20:40,113,홍대입구역 2번출구 앞,24.0,2019-11-15 20:53,101,(구)합정동 주민센터,1.000000,12.0,2280.000000
418,SPB-24467,2019-11-15 21:55,152,마포구민체육센터 앞,18.0,2019-11-15 22:05,101,(구)합정동 주민센터,1.000000,10.0,1180.000000
419,SPB-17570,2019-11-15 22:16,391,정동길입구,7.0,2019-11-15 23:04,101,(구)합정동 주민센터,5.000000,48.0,8100.000000

In [43]:
# 이용거리 데이터 중에 결측치를 이용거리 평균값으로 대체하기
df['이용거리'].fillna(df['이용거리'].mean())

0      1100.000000
1      1420.000000
2      2679.678218
3      1380.000000
4      1650.000000
          ...
415    2200.000000
416    2679.678218
417    2280.000000
418    1180.000000
419    8100.000000
Name: 이용거리, Length: 420, dtype: float64